# Generated by Django 4.2.16 on 2024-10-16 19:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0002_alter_highlight_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='image',
            field=cloudinary.models.CloudinaryField(default='website/uploads/default_image.webp', max_length=255, verbose_name='Image'),
        ),
    ]
