# Generated by Django 4.2.16 on 2024-10-12 18:43

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanAirResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_title', models.CharField(max_length=120)),
                ('resource_link', models.URLField(blank=True, null=True)),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='cleanair/resources/')),
                ('author_title', models.CharField(blank=True, default='Created By', max_length=40, null=True)),
                ('resource_category', models.CharField(choices=[('toolkit', 'ToolKit'), ('technical_report', 'Technical Report'), ('workshop_report', 'Workshop Report'), ('research_publication', 'Research Publication')], default='technical_report', max_length=40)),
                ('resource_authors', models.CharField(default='AirQo', max_length=200)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForumEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='CLEAN-Air Forum', max_length=100)),
                ('title_subtext', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('introduction', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('speakers_text_section', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('committee_text_section', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('partners_text_section', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('registration_link', models.URLField(blank=True)),
                ('schedule_details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('registration_details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sponsorship_opportunities_about', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sponsorship_opportunities_schedule', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sponsorship_opportunities_partners', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sponsorship_packages', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('travel_logistics_vaccination_details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('travel_logistics_visa_details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('travel_logistics_accommodation_details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('glossary_details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('background_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='BackgroundImage')),
                ('location_name', models.CharField(blank=True, max_length=100)),
                ('location_link', models.URLField(blank=True)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ForumResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_title', models.CharField(max_length=120)),
                ('resource_authors', models.CharField(default='AirQo', max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('forum_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_resources', to='cleanair.forumevent')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('sub_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('forum_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='cleanair.forumevent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=70)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.IntegerField(default=1)),
                ('forum_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supports', to='cleanair.forumevent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(null=True)),
                ('session_title', models.CharField(max_length=150)),
                ('session_details', ckeditor.fields.RichTextField(null=True)),
                ('order', models.IntegerField(default=1)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='cleanair.program')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResourceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_title', models.CharField(max_length=120)),
                ('order', models.IntegerField(default=1)),
                ('forum_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_sessions', to='cleanair.forumresource')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_summary', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='cleanair/resources/')),
                ('order', models.IntegerField(default=1)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_files', to='cleanair.resourcesession')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Speaker', 'Speaker'), ('Committee Member', 'Committee Member'), ('Key Note Speaker', 'Key Note Speaker'), ('Speaker and Committee Member', 'Speaker And Committee Member'), ('Committee Member and Key Note Speaker', 'Committee Member And Key Note Speaker')], default='Speaker', max_length=50)),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='PersonImage')),
                ('twitter', models.URLField(blank=True)),
                ('linked_in', models.URLField(blank=True)),
                ('order', models.IntegerField(default=1)),
                ('forum_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='cleanair.forumevent')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ForumPartnerImage')),
                ('name', models.CharField(max_length=70)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('Funding Partner', 'Funding Partner'), ('Host Partner', 'Host Partner'), ('Co-Convening Partner', 'Co Convening Partner'), ('Sponsor Partner', 'Sponsor Partner')], default='Funding Partner', max_length=50)),
                ('forum_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='cleanair.forumevent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='cleanair.engagement')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='engagement',
            name='forum_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='cleanair.forumevent'),
        ),
    ]
