# Generated by Django 4.2.16 on 2024-10-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumevent',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to='cleanair/events/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_logo',
            field=models.FileField(blank=True, null=True, upload_to='cleanair/events/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='cleanair/events/'),
        ),
    ]
