# Generated by Django 4.2.16 on 2024-10-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0002_alter_forumevent_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='cleanair/resources/'),
        ),
    ]
