# Generated by Django 4.2.16 on 2024-10-16 19:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0003_alter_resourcefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanairresource',
            name='resource_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='BackgroundImage'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ForumPartnerImage'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='PersonImage'),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='BackgroundImage'),
        ),
    ]
