# Generated by Django 4.2.16 on 2024-10-16 19:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('externalTeam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalteammember',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
    ]
