version: "3.3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env # Use DATABASE_URL or other env vars from the backend's .env file
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env # Use frontend environment variables
    depends_on:
      - backend
