######## For development purposes only.#######
# Ensure to install Docker and Docker Compose before running this file.
# This file is used to define the services and their configurations for the AirQo-website project.
# It is used by the docker-compose command to start and manage the containers.
#
# To start the containers, run the following command in the terminal:
#   docker-compose up -d
#
# To stop the containers, run the following command in the terminal:
#   docker-compose down
#
# To view the logs of a container, run the following command in the terminal:
#   docker-compose logs <service-name>
#
# To view the logs of all containers, run the following command in the terminal:
#   docker-compose logs --follow
#
# To view the status of the containers, run the following command in the terminal:
#   docker-compose ps

version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/.env # Backend-specific environment file
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build
    volumes:
      - ./frontend:/app/frontend
    env_file:
      - ./frontend/.env # Frontend-specific environment file
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    env_file:
      - ./backend/.env # Reference the backend .env file for database environment variables
    ports:
      - "2023:2023"
