# Generated by Django 4.2.16 on 2024-10-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africancities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='africancountry',
            name='country_flag',
            field=models.FileField(blank=True, null=True, upload_to='african_countries/flags/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='content_images/'),
        ),
    ]
