# Generated by Django 4.2.16 on 2024-10-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_session_event_session_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_details',
            field=models.TextField(),
        ),
    ]
