# Generated by Django 4.2.16 on 2024-10-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_event_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to='events/images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.FileField(blank=True, null=True, upload_to='events/images/'),
        ),
    ]
