# Generated by Django 4.2.16 on 2024-10-16 19:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_partnerlogo_partner_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='background_image',
            field=cloudinary.models.CloudinaryField(default='website/uploads/default_image.webp', max_length=255, verbose_name='BackgroundImage'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=cloudinary.models.CloudinaryField(default='website/uploads/default_image.webp', max_length=255, verbose_name='EventImage'),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='partner_logo',
            field=cloudinary.models.CloudinaryField(default='website/uploads/default_image.webp', max_length=255, verbose_name='PartnerImage'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
    ]
