# Generated by Django 4.2.16 on 2024-10-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_remove_event_is_deleted_remove_inquiry_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(default='ee6f01aa7e1e40f1913897c83cf7305d', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='id',
            field=models.CharField(default='ee6f01aa7e1e40f1913897c83cf7305d', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='id',
            field=models.CharField(default='ee6f01aa7e1e40f1913897c83cf7305d', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.CharField(default='ee6f01aa7e1e40f1913897c83cf7305d', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.CharField(default='ee6f01aa7e1e40f1913897c83cf7305d', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default='ee6f01aa7e1e40f1913897c83cf7305d', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
