# Generated by Django 4.2.16 on 2024-10-17 20:31

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_event_id_alter_inquiry_id_alter_partnerlogo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_details',
            field=django_quill.fields.QuillField(default='No details available'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(default='2a3a00ea5ae34ab78aaa635e550acae4', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='id',
            field=models.CharField(default='2a3a00ea5ae34ab78aaa635e550acae4', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='id',
            field=models.CharField(default='2a3a00ea5ae34ab78aaa635e550acae4', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.CharField(default='2a3a00ea5ae34ab78aaa635e550acae4', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.CharField(default='2a3a00ea5ae34ab78aaa635e550acae4', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default='2a3a00ea5ae34ab78aaa635e550acae4', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_details',
            field=django_quill.fields.QuillField(default='No details available'),
        ),
    ]
