# Generated by Django 4.2.16 on 2024-10-11 15:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_remove_career_unique_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletpoint',
            name='bullet',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='career',
        ),
        migrations.AddField(
            model_name='career',
            name='career_details',
            field=ckeditor.fields.RichTextField(default='Details coming soon.'),
        ),
        migrations.DeleteModel(
            name='BulletDescription',
        ),
        migrations.DeleteModel(
            name='BulletPoint',
        ),
        migrations.DeleteModel(
            name='JobDescription',
        ),
    ]
