# Generated by Django 4.2.16 on 2024-10-11 16:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_remove_bulletpoint_bullet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='career_details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
