# Generated by Django 4.2.16 on 2024-10-11 17:16

import apps.publications.models
import cloudinary.models
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.CharField(default=apps.publications.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('resource_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file')),
                ('link_title', models.CharField(blank=True, default='Read More', max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('research', 'Research'), ('technical', 'Technical'), ('policy', 'Policy'), ('guide', 'Guide'), ('manual', 'Manual')], default='research', max_length=40, null=True)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
