# Generated by Django 4.2.16 on 2024-10-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_publication_resource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='resource_file',
            field=models.FileField(blank=True, null=True, upload_to='publications/files/'),
        ),
    ]
