# Generated by Django 4.2.16 on 2024-10-12 12:07

import apps.partners.models
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.CharField(default=apps.partners.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('partner_logo', models.FileField(blank=True, null=True, upload_to='partners/logos/')),
                ('partner_image', models.FileField(blank=True, null=True, upload_to='partners/images/')),
                ('partner_name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('partner_link', models.URLField(blank=True, null=True)),
                ('unique_title', models.CharField(blank=True, max_length=100, null=True)),
                ('website_category', models.CharField(blank=True, choices=[('airqo', 'AirQo'), ('cleanair', 'CleanAir')], default='airqo', max_length=40, null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerDescription',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.CharField(default=apps.partners.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descriptions', to='partners.partner')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
