# Generated by Django 4.2.16 on 2024-10-12 12:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='created',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='unique_title',
        ),
        migrations.RemoveField(
            model_name='partnerdescription',
            name='created',
        ),
        migrations.RemoveField(
            model_name='partnerdescription',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='partnerdescription',
            name='modified',
        ),
        migrations.AddField(
            model_name='partner',
            name='type',
            field=models.CharField(blank=True, choices=[('partnership', 'Partnership'), ('collaboration', 'Collaboration'), ('policy', 'Policy'), ('funder', 'Funder'), ('research', 'Research'), ('ca-network', 'Clean Air Network Partner'), ('ca-support', 'Clean Air Supporting Partner'), ('ca-forum', 'Clean Air Policy Forum'), ('ca-private-sector', 'Clean Air Private Sector')], default='partnership', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='PartnerImage'),
        ),
    ]
