# Generated by Django 4.2.16 on 2024-10-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_remove_partner_created_remove_partner_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_image',
            field=models.FileField(blank=True, null=True, upload_to='partners/images/'),
        ),
    ]
