# Generated by Django 4.2.16 on 2024-10-16 19:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_partner_partner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='PartnerImage'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_logo',
            field=cloudinary.models.CloudinaryField(default='website/uploads/default_image.webp', max_length=255, verbose_name='PartnerLogo'),
        ),
    ]
