# Generated by Django 4.2.16 on 2024-10-14 22:54

import apps.FAQ.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.CharField(default=apps.FAQ.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=150)),
                ('answer', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
