# Generated by Django 4.2.16 on 2024-10-10 07:13

import cloudinary.models
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_deleted', models.BooleanField(default=False)),
                ('article_title', models.CharField(max_length=100)),
                ('article_intro', models.CharField(blank=True, max_length=200, null=True)),
                ('article_link', models.URLField(blank=True, null=True)),
                ('date_published', models.DateField()),
                ('publisher_logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='PublisherLogo')),
                ('order', models.IntegerField(default=1)),
                ('website_category', models.CharField(blank=True, choices=[('airqo', 'AirQo'), ('cleanair', 'CleanAir')], default='airqo', max_length=40, null=True)),
                ('article_tag', models.CharField(blank=True, choices=[('none', 'None'), ('featured', 'Featured')], default='none', max_length=40, null=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
