# Generated by Django 4.2.16 on 2024-10-10 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('press', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_press_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='press',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_press_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
