# Generated by Django 4.2.16 on 2024-10-11 10:08

import apps.press.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0003_alter_press_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='id',
            field=models.CharField(default=apps.press.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
