# Generated by Django 4.2.16 on 2024-10-16 19:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0005_alter_press_publisher_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='publisher_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='PublisherLogo'),
        ),
    ]
